#ifndef RAXML_STARTTREEHEURISTIC_HPP_
#define RAXML_STARTTREEHEURISTIC_HPP_

#include <optional>

#include "../../Tree.hpp"
#include "../../Options.hpp"
#include "../Threadpool.hpp"

// forward declaration of RaxmlInstance
struct RaxmlInstance;

// forward declaration to avoid cyclic header inclusion.
// only implementations of subclasses may import this type, headers must only refer to the forward declaration.
class SharedBatchResources;

/**
 * Strategy interface to start tree generation for bandits.
 */
class StartTreeHeuristic {
public:
    virtual ~StartTreeHeuristic() = default;

    /**
     * @param batch_name name of the batch that uses this heuristic
     * @param inner inner heuristic stage (which will be executed first)
     * @param num_trees number of trees inferred by this instance
     * @param starting_seed seed for the first tree in the batch, further seeds are incremented by one
     *
     */
    StartTreeHeuristic(std::string batch_name, const unsigned int num_trees, const unsigned int starting_seed,
                       std::unique_ptr<StartTreeHeuristic> inner)
        : batch_name(std::move(batch_name)),
          seeds(num_trees),
          inner(std::move(inner)),
          num_trees(num_trees) {
        std::iota(seeds.begin(), seeds.end(), starting_seed);
    }

    StartTreeHeuristic(const StartTreeHeuristic &other) = delete;

    StartTreeHeuristic &operator=(const StartTreeHeuristic &other) = delete;

    StartTreeHeuristic(StartTreeHeuristic &&other) noexcept = default;

    StartTreeHeuristic &operator=(StartTreeHeuristic &&other) noexcept = default;

    /**
     * Run the entire inference heuristic defined by this (and all contained) instances.
     *
     * @param tree reference to tree object that is to be generated. It will get overwritten with the generated tree.
     * @param tree_id batch-internal index of the tree. This can be used to index datastructures which hold instances
     *        per batch tree.
     * @param instance raxml instance required for parsimony tree generation
     * @param context task group context, used for synchronization of workers working on the same `TunedBatch`
     * @param resources `SharedBatchResources` instance of the treeset optimizer
     * @param worker_id raxml-instance-global id of the current thread's worker. Used for work distribution.
     * @param thread_id thread id within the current worker. Used for work distribution.
     */
    void generate(Tree &tree, unsigned int tree_id, const RaxmlInstance &instance,
                  const TaskGroup &context, SharedBatchResources &resources, unsigned int worker_id,
                  unsigned int thread_id);

    /**
     * Calculate the cumulative wall-time spent on all inferred trees across the entire heuristic.
     * Cumulative time is the time spent on each tree as if they were inferred sequentially.
     *
     * @return the total cumulative wall-time across the entire heuristic
     */
    [[nodiscard]] unsigned int get_total_wall_time() const;

    /**
     * Implementation of the concrete inference strategy. Inference will modify the `tree` argument, which is passed
     * to each implementation in the decorator chain. Subclasses of `ImprovingHeuristic` have to implement this
     * method.
     *
     * @param tree reference to tree object that is to be generated. It will get overwritten with the generated tree.
     * @param tree_id batch-internal index of the tree. This can be used to index datastructures which hold instances
     *        per batch tree.
     * @param instance raxml instance required for parsimony tree generation
     * @param context task group context, used for synchronization of workers working on the same `TunedBatch`
     * @param resources `SharedBatchResources` instance of the treeset optimizer
     * @param worker_id raxml-instance-global id of the current thread's worker. Used for work distribution.
     * @param thread_id thread id within the current worker. Used for work distribution.
     */
    virtual void do_generate(Tree &tree, unsigned int tree_id, const RaxmlInstance &instance,
                             const TaskGroup &context, SharedBatchResources &resources, unsigned int worker_id,
                             unsigned int thread_id) = 0;

protected:
    /**
     * Batch name of the batch that owns this strategy, used for log output.
     */
    std::string batch_name;

    /**
     * All seeds for the trees generated by this heuristic. Accessible with their id.
     */
    std::vector<unsigned int> seeds;

private:
    /**
     * Wall-time spent on the current heuristic. This is cumulative across all trees, even if they were processed in
     * parallel.
     */
    std::unique_ptr<std::atomic_uint> cumulative_wall_time = std::make_unique<std::atomic_uint>(0);

    /**
     * Previous stage of the decorator chain. If this pointer is not null, the strategy contained in this pointer is
     * called before the current stage is executed.
     */
    std::unique_ptr<StartTreeHeuristic> inner = {};

    /**
     * Number of trees inferred by this instance
     */
    unsigned int num_trees;
};


#endif //RAXML_STARTTREEHEURISTIC_HPP_
