#include "Bandit.hpp"
#include "TunedBatch.hpp"

void Bandit::apply_parameters(TunedBatch &batch) const {
    // TODO: replace meta parameters in TunedBatch with instance of MetaParameters and make it resettable
    //  then load it from here so batches can be pre-generated by the heuristic and then a bandit can be chosen.
}

double Bandit::get_mean_throughput() const {
    double expectation = 0.0;

    for (auto& sample : this->samples) {
        // the cost function is TIME / #TREES (time spent per plausible tree), but the throughput (which is our reward
        // function) is the inverse of that: 1 / (TIME / #TREES)) = #TREES / TIME, with a reward of 0 if no plausible
        // trees are found
        expectation += static_cast<double>(sample.plausible_trees) / static_cast<double>(sample.time_spent);
    }

    return expectation / this->samples.size();
}

void Bandit::take_measurement(const TunedBatch &batch) {
    this->samples.emplace_back(batch.elapsed_wall_time(), batch.get_plausible_tree_count());
}
