#include "Bandit.hpp"
#include "TunedBatch.hpp"

void Bandit::apply_parameters(TunedBatch &batch) const {
    // TODO: replace meta parameters in TunedBatch with instance of MetaParameters and make it resettable
    //  then load it from here so batches can be pre-generated by the heuristic and then a bandit can be chosen.
}

double Bandit::get_mean() const {
    double expectation = 0.0;

    for (auto& sample : this->samples) {
        expectation += static_cast<double>(sample.time_spent) / static_cast<double>(sample.plausible_trees);
    }

    return expectation / this->samples.size();
}

void Bandit::take_measurement(const TunedBatch &batch) {
    this->samples.emplace_back(batch.elapsed_wall_time(), batch.get_plausible_tree_count());
}
