#include "TreesetHeuristic.hpp"
#include "TunedBatch.hpp"

constexpr unsigned int BATCH_SIZE = 32;

/**
 * A collection of measurements associated with one TunedBatch instance.
 * The benchmark tracks a series of wall-times for tree inference and the improvements in plausible tree counts.
 *
 * We can use those times to obtain the best parameters for batches that will yield the most plausible trees with the
 * least wall-time spent.
 */
class BatchBenchmark {
public:
    std::vector<unsigned int> cost{};

    /**
     * Add a data point to the benchmark.
     * @param plausible_trees How many plausible trees were reached (total)
     * @param wall_time How many nanoseconds did it take to obtain the plausible tree count (total)
     */
    void add_data_point(const unsigned int plausible_trees, const unsigned int wall_time) {
        cost.push_back(wall_time / plausible_trees);
    }

    /**
     * Get the index of the data point where the cost (i.e. the time spent per plausible tree) is lowest.
     * @return 0-based index of the datapoint of minimum time spent per plausible tree.
     */
    unsigned int get_cheapest_point() const {
        return distance(cost.begin(), min_element(cost.begin(), cost.end()));
    }

    /**
     * @return Returns true, if the last two data points did not improve the time per plausible tree metric,
     *         meaning doing more work does not speed up computation.
     */
    bool is_converged() const {
        const auto min = min_element(cost.begin(), cost.end());
        return distance(min, cost.end()) > 2;
    }
};

void TreesetHeuristic::infer_treeset(RaxmlInstance &instance, const Options &opts, CheckpointManager &cm,
                                     LoadBalancer &load_balancer) {
    // copy SPR parameters from local search state
    auto search_state = SearchState();
    auto &spr_params = search_state.spr_params;
    spr_params.ntopol_keep = 20;
    spr_params.subtree_cutoff = opts.spr_cutoff;
    spr_params.radius_min = 0;
    spr_params.radius_max = 20;
    spr_params.thorough = false;
    spr_params.lh_epsilon_brlen_full = opts.lh_epsilon;
    spr_params.lh_epsilon_brlen_triplet = opts.lh_epsilon_brlen_triplet;

    // generate trees depending on the seed. Note that the normal starting trees are generated by seeding srand() and
    // then generating seeds using rand(), so we won't be creating duplicates by starting over from the random_seed.
    auto seed_offset = opts.random_seed;

    // keep all batches around
    std::vector<TunedBatch> finished_batches;

    while (tuning_phase != FINALIZED) {
        auto batch = TunedBatch(this->greedy_spr, this->skip_model, this->num_spr, seed_offset, BATCH_SIZE, spr_params, this->recommended_thread_count(),
                                         this->recommended_worker_count(), msa, persite_loglh);
        seed_offset += BATCH_SIZE;
        batch.generate_starting_trees(instance, opts, load_balancer, tip_msa_idmap);

        BatchBenchmark benchmark;

        switch (tuning_phase) {
            case TUNE_BASELINE:
                if (batch.is_plausible(opts)) {
                    LOG_INFO_TS << "Most starting trees are already plausible; topology optimization unnecessary" << std::endl;
                    this->accept_starting_trees = true;
                    tuning_phase = FINALIZED;
                    break;
                }

                LOG_INFO_TS << "Starting trees generally implausible; topology optimization necessary" << std::endl;

                do {
                    benchmark.add_data_point(batch.plausible_tree_count(), batch.elapsed_wall_time());

                    this->num_spr += 1;
                    batch.target_num_spr = this->num_spr;
                    batch.infer_batch(opts);
                } while (!batch.is_plausible(opts) && !benchmark.is_converged());

                if (benchmark.is_converged()) {
                    LOG_INFO_TS << "after " << benchmark.get_cheapest_point() << " spr rounds, plausibility converged."
                            << std::endl;
                } else {
                    LOG_INFO_TS << benchmark.get_cheapest_point() << " spr rounds sufficient." << std::endl;
                }

                LOG_INFO_TS << "estimated time per FAST chunk: " << batch.elapsed_wall_time() << "ms." << std::endl;

                tuning_phase = TUNE_GREEDY;
                this->greedy_spr = true;
                break;
            case TUNE_GREEDY:
                batch.infer_batch(opts);
                if (!batch.is_plausible(opts)) {
                    LOG_INFO_TS << "Greedy spr yielded implausible trees, reverting to Top-K" << std::endl;
                    this->greedy_spr = false;
                } else {
                    LOG_INFO_TS << "Greedy spr rounds yielded plausible trees. Disabling Top-K." << std::endl;
                }

                this->skip_model = true;
                this->tuning_phase = TUNE_MODEL_OPT;
                break;
            case TUNE_MODEL_OPT:
                batch.inherit_model(*(finished_batches.end() - 1));
                batch.infer_batch(opts);
                if (!batch.is_plausible(opts)) {
                    LOG_INFO_TS << "Skipping model optimization yielded implausible trees, reverting to per-tree model optimization." << std::endl;
                    this->skip_model = false;
                } else {
                    LOG_INFO_TS << "Skipping model optimization yielded plausible trees, disabling per-tree model optimization." << std::endl;
                }

                this->tuning_phase = FINALIZED;
                break;
            case FINALIZED:
                break;
        }

        finished_batches.push_back(std::move(batch));
    }

    LOG_INFO_TS << "treeset inference complete." << std::endl;
}

int TreesetHeuristic::recommended_thread_count() {
    // TODO add parameters to options containing the max thread count, which we just assign to the single worker per rank
    return 8;
}

int TreesetHeuristic::recommended_worker_count() {
    // TODO this is only true for the tuning phase
    return 1;
}
