#ifndef RAXML_TREESETOPTIMIZER_HPP_
#define RAXML_TREESETOPTIMIZER_HPP_

#include <vector>
#include "Bandit.hpp"
#include "BatchQueue.hpp"
#include "MultiArmedBandit.hpp"
#include "../loadbalance/LoadBalancer.hpp"
#include "../Checkpoint.hpp"
#include "Threadpool.hpp"
#include "SharedBatchResources.hpp"

constexpr unsigned int DEFAULT_BATCH_SIZE = 16;

/**
 * SPR radius used when pythia is disabled. Fast SPR will multiply this radius with 2.
 */
constexpr unsigned int DEFAULT_ADAPTIVE_RADIUS = 10;

class TreesetOptimizer {
protected:
    /**
     * A threadpool which takes control of the main thread, forks, and then works tasks generated by next_work_unit
     * until any task shuts down the thread pool. It then joins all threads and returns, finishing the core algorithm.
     */
    ThreadPool pool;

    /**
     * Resources shared between batches, either group-local or thread-safe resources that aren't specific to the batch
     * (like AU test instances that can be reused, or profiler that need to be shared).
     */
    SharedBatchResources shared_batch_resources;

    /**
     * Reference to RaxmlInstance that we require for some of the optimization routines. We don't access or modify it,
     * we just pass it to baseline algorithms.
     */
    RaxmlInstance &instance;

    /**
     * Reference to the user options which are required for all optimization steps
     */
    const Options &opts;

    /**
     * Manages the available batches that can be used by the bandits.
     */
    BatchQueue batch_queue;

    /**
     * Pythia score of the MSA or -1.0 if pythia is disabled.
     */
    double pythia_score;

    /**
     * The number of plausible trees to infer in total.
     */
    const unsigned int target_tree_count;

    MultiArmedBandit<std::shared_ptr<MultiArmedBandit<MetaParameters> > > hierarchical_mab;

    std::shared_ptr<MultiArmedBandit<MetaParameters> > parsimony = std::make_shared<MultiArmedBandit<
        MetaParameters> >();

    std::shared_ptr<MultiArmedBandit<MetaParameters> > nni_mab = std::make_shared<MultiArmedBandit<
        MetaParameters> >();

    /**
     * A multi-armed bandit instance that contains aggressive heuristics
     */
    std::shared_ptr<MultiArmedBandit<MetaParameters> > light_mab = std::make_shared<MultiArmedBandit<
        MetaParameters> >();

    /**
    * A multi-armed bandit instance that contains slower heuristics
    */
    std::shared_ptr<MultiArmedBandit<MetaParameters> > low_mab = std::make_shared<MultiArmedBandit<
        MetaParameters> >();

    /**
     * A multi-armed bandit instance that contains light and mixed heuristics with tree constrains
     */
    std::shared_ptr<MultiArmedBandit<MetaParameters> > constrained_mab = std::make_shared<MultiArmedBandit<
        MetaParameters> >();

    /**
     * A multi-armed bandit instance that runs a dynamic number of SPR rounds
     */
    std::shared_ptr<MultiArmedBandit<MetaParameters> > dynamic_mab = std::make_shared<MultiArmedBandit<
            MetaParameters> >();

    /**
     * Fallback to fast raxml
     */
    std::shared_ptr<MultiArmedBandit<MetaParameters> > fallback_fast_mab = std::make_shared<MultiArmedBandit<
        MetaParameters> >();

    /**
     * A list of bandit arms that are successors to previous arms in case they are not yet optimal.
     * They are each given a rank, and are added if the best performing bandit does not have high success rate.
     * Each time, all bandits with a rank as high or lower than the number of currently active bandits are added.
     */
    std::vector<std::tuple<unsigned int, std::string, std::shared_ptr<MultiArmedBandit<MetaParameters> > > > successors;

    /**
     * Initialize the bandit algorithms we use during the inference. These depend on the parameters derivded from initial
     * starting tree inference in `prepare_initial_batches()`
     */
    void initialize_bandits();

    /**
     * Main method for the threadpool workers.
     * This method runs one batch and then handles the updates to the MABs.
     * It is bound into a BatchTask by next_work_unit.
     */
    void run_batch(Bandit<std::shared_ptr<MultiArmedBandit<MetaParameters> > > &mab, Bandit<MetaParameters> &bandit,
                   TunedBatch &batch, TaskGroup &context, unsigned int worker_id, unsigned int thread_id);

    /**
     * Select a unit of work of the current state of the optimizer algorithm.
     * This advances the multi-armed bandits, selects one using the current amount of learned information, and
     * selects a batch to run the bandit against.
     * It curries the necessary parameters to the main method of the batch (run_batch) leaving an instance of a BatchTask.
     *
     * @return the main method of the next tuned batch to call by all threads of the work group that called this method.
     */
    BatchTask next_work_unit();

    /**
     * Check whether we should insert new arms into the MAB depending on the performance of the current bandit arm.
     * This implements a heuristic that enables exploration for new arms if they have potential to be useful within
     * the algorithm.
     * This enables us to skip exploring arms that have no potential gain over currently explored arms.
     *
     */
    void check_mab_modification();

public:
    /**
     *
     * @param instance Reference to the RAxML-ng instance
     * @param opts Reference to the user options structure
     * @param msa multiple sequence alignment
     * @param tip_msa_idmap Reference to the tip ID mapping of the MSA.
     * @param persite_loglh reference to the per-site log likelihoods of the originally computed trees
     * @param load_balancer Reference to the user-configured fine-grained load balancer.
     * @param pythia_score the pythia difficulty score or -1.0 if it was disabled by the user
     * @param target_tree_count The number of plausible trees to infer
     * @param starting_seed the tree generating seed for the first tree. Subsequent seeds are incremented by one.
     */
    TreesetOptimizer(RaxmlInstance &instance,
                     Options &opts,
                     const std::shared_ptr<PartitionedMSA> &msa,
                     const Tree &tree,
                     IDVector &tip_msa_idmap,
                     const std::vector<std::vector<doubleVector> > &persite_loglh,
                     LoadBalancer &load_balancer,
                     const double pythia_score,
                     const unsigned int target_tree_count,
                     const unsigned long long starting_seed) : pool(ThreadPool(
                                                                   [this] {
                                                                       return this->next_work_unit();
                                                                   }, opts.treeset_threads, opts.treeset_workers,
                                                                   opts.treeset_groups)),
                                                               shared_batch_resources(
                                                                   opts.treeset_groups,
                                                                   opts.treeset_workers,
                                                                   opts.treeset_threads,
                                                                   opts, msa, tree,
                                                                   persite_loglh,
                                                                   DEFAULT_BATCH_SIZE,
                                                                   starting_seed),
                                                               instance(instance),
                                                               opts(opts),
                                                               batch_queue(
                                                                   instance, opts, make_shared<IDVector>(tip_msa_idmap),
                                                                   load_balancer, msa,
                                                                   make_shared<std::vector<std::vector<
                                                                       doubleVector> > >(persite_loglh), starting_seed,
                                                                   DEFAULT_BATCH_SIZE),
                                                               pythia_score(pythia_score),
                                                               target_tree_count(target_tree_count) {
    }

    /**
     * Run the treeset optimizer to infer K plausible trees.
     */
    void run();

    /**
     * Obtain all trees (plausible and rejected) inferred during the treeset optimization into a common vector and
     * return the vector.
     * This does not include the reference trees.
     *
     * @return A new vector instance containing all tree topologies.
     */
    std::vector<Tree> get_all_trees() const;

    /**
     * Obtain all plausible trees into a common vector and return the vector.
     * This does not include the reference trees.
     *
     * @return A new vector instance containing all plausible tree topologies.
     */
    std::vector<Tree> get_plausible_trees() const;

    /**
     * The hierarchical bandit counts how many iterations of the bandit algorithm have been completed. Modifications
     * of the bandit shouldn't happen too often, so we ensure there is a minimum amount of iterations between adding
     * new bandits, such that the new bandit can be tested before adding new ones.
     */
    unsigned int last_mab_modification = 0;
};


#endif //RAXML_TREESETOPTIMIZER_HPP_
