#include "TreesetHeuristic.hpp"
#include "TunedBatch.hpp"

constexpr unsigned int BATCH_SIZE = 16;

void TreesetHeuristic::infer_treeset(RaxmlInstance &instance, const Options &opts, CheckpointManager &cm,
                                     LoadBalancer &load_balancer) {
    // copy SPR parameters from local search state
    const auto &search_state = cm.search_state();
    const auto spr_params = search_state.spr_params;

    // generate trees depending on the seed. Note that the normal starting trees are generated by seeding srand() and
    // then generating seeds using rand(), so we won't be creating duplicates by starting over from the random_seed.
    auto seed_offset = opts.random_seed;

    auto batch = new TunedBatch(this->greedy_spr, this->skip_model, this->skip_model, seed_offset, BATCH_SIZE, spr_params, this->recommended_thread_count(),
                                 this->recommended_worker_count(), msa, persite_loglh);
    seed_offset += BATCH_SIZE;
    batch->generate_starting_trees(instance, opts, load_balancer, tip_msa_idmap);

    while (tuning_phase != FINALIZED) {

        switch (tuning_phase) {
            case TUNE_STARTING_TREES:
                if (batch->is_plausible(opts)) {
                    LOG_INFO_TS << "Most starting trees are already plausible; topology optimization unnecessary" << std::endl;
                    this->accept_starting_trees = true;
                    tuning_phase = FINALIZED;
                    break;
                }

                LOG_INFO_TS << "Starting trees generally implausible; topology optimization necessary" << std::endl;

                // fall through
            case TUNE_GREEDY:
                batch->infer_batch(instance, opts, load_balancer, this->tip_msa_idmap);
                if (!batch->is_plausible(opts)) {
                    LOG_INFO_TS << "Greedy SPR yielded implausible trees, reverting to Top-K" << std::endl;
                    this->greedy_spr = false;
                } else {
                    LOG_INFO_TS << "Greedy SPR rounds yielded plausible trees. Disabling Top-K." << std::endl;
                }

                this->skip_model = true;
                this->tuning_phase = TUNE_MODEL_OPT;
                break;
            case TUNE_MODEL_OPT:
                batch->infer_batch(instance, opts, load_balancer, this->tip_msa_idmap);
                if (!batch->is_plausible(opts)) {
                    LOG_INFO_TS << "Skipping model optimization yielded implausible trees, reverting to per-tree model optimization." << std::endl;
                    this->skip_model = false;
                } else {
                    LOG_INFO_TS << "Skipping model optimization yielded plausible trees, disabling per-tree model optimization." << std::endl;
                }

                this->tuning_phase = TUNE_SPR;
                break;
            case TUNE_SPR:
                // TODO implement SPR tuning
                batch->infer_batch(instance, opts, load_balancer, this->tip_msa_idmap);
                this->tuning_phase = FINALIZED;
            case FINALIZED:
                break;
        }

        batch = new TunedBatch(this->greedy_spr, this->skip_model, this->num_spr, seed_offset, BATCH_SIZE, spr_params, this->recommended_thread_count(),
                                 this->recommended_worker_count(), msa, persite_loglh);
        seed_offset += BATCH_SIZE;
        batch->generate_starting_trees(instance, opts, load_balancer, tip_msa_idmap);
    }

    LOG_INFO_TS << "treeset inference complete." << std::endl;
}

int TreesetHeuristic::recommended_thread_count() {
    // TODO add parameters to options containing the max thread count, which we just assign to the single worker per rank
    return 8;
}

int TreesetHeuristic::recommended_worker_count() {
    // TODO this is only true for the tuning phase
    return 1;
}
