#include "StartTrees.hpp"
#include <optional>
#include "../../TreeInfo.hpp"

void StartTrees::do_optimize(std::optional<TreeInfo> &tree, const unsigned int tree_id, const Options &opts, const TaskGroup &context, SharedBatchResources &, const unsigned int, const unsigned int thread_id) {
    assert(!tree.has_value());

    // barrier so we dont start building tree-info objects without finished trees (since the thread assignment changes,
    // so threads could be ready to work while their tree is still being generated by another).
    context.enter_barrier();

    // create context for tree inference and assign the initial model
    if (this->model_override) {
        const auto model = Model(*this->model_override);
        tree.emplace(opts, this->batch_start_trees->at(tree_id), *this->msa,
                                                 *this->tip_msa_idmap, this->part_assignments->at(thread_id), &model);
    } else {
        tree.emplace(opts, this->batch_start_trees->at(tree_id), *this->msa,
                                                 *this->tip_msa_idmap, this->part_assignments->at(thread_id));
        assign_models(*tree, *this->initial_model);
    }
}
